name: EBAC CI MOBILE

on:
    push:
        branches: [ci]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
           - uses: actions/checkout@v4
           - uses: actions/setup-node@v4

             with:
                node-version: '24'

           - name: Install Dependencies
             run: npm install

           - name: Run Test
             env:
              ENVIRONMENT: sauceLabs
              PLATFORM: Android
              REPORTER: true
              SAUCE_USER: ${{env.SAUCE_USER}}
              SAUCE_KEY: ${{env.SAUCE_KEY}}
             run: npm run test:report
           - name: Publish Report
             uses: peaceiris/actions-github-pages@v3.1.12
             if: always()
             with:
                github_token: $${{secrets.GITHUB_TOKEN}}
                publish_dir: ./allure-report
